---

apiVersion: v1
kind: Service
metadata:
  name: compass
  labels:
    app: compass
spec:
  clusterIP: None
  selector:
    app: compass

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compass
spec:
  serviceName: "compass"
  replicas: 1
  selector:
    matchLabels:
      app: compass
  template:
    metadata:
      labels:
        app: compass
    spec:
      containers:
        - name: compass
          image: digitalrasta/compass:aws-17
          command: ["/entrypoint.sh"]
          args: ["-layers", "/layers", "-statePath", "/data/compass.state", "-sigMode", "CURLP27", "-powMode", "CURLP81", "-mwm", "7","-security", "1" ,"-seed" ,"SEED99999999999999999999999999999999999999999999999999999999999999999999999999999", "-tick", "90000" ,"-host" ,"http://iri-03:14265","-broadcast"]
          volumeMounts:
            - name: data
              mountPath: /data
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: eu-west-1c
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

