---

apiVersion: v1
kind: Service
metadata:
  name: iri-02
  labels:
    app: iri-02
spec:
  ports:
    - port: 14265
      name: iri-api
    - port: 14600
      name: iri-peering-udp
    - port: 15600
      name: iri-peering-tcp
  clusterIP: None
  selector:
    app: iri-02

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iri-02
spec:
  serviceName: "iri-02"
  replicas: 1
  selector:
    matchLabels:
      app: iri-02
  template:
    metadata:
      labels:
        app: iri-02
    spec:
      containers:
        - name: backup
          image: digitalrasta/backup:aws-11
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          volumeMounts:
            - name: data
              mountPath: /data
            - name: dockersock
              mountPath: "/var/run/docker.sock"
        - name: iri
          image: iotaledger/iri:latest
          args: ["-n", "tcp://iri-03:15600,tcp://iri-01:15600","--testnet", "true", "--remote", "true", "--testnet-coordinator", "9LFYANWKXIKHKYETYBZQPI9SSBZA9KJCOKLMPFUXNWUTULJVOAKHPWVYIVKDCXUYPLFBBHHUFHOESJWNZ", "--testnet-coordinator-security-level", "1", "--testnet-coordinator-signature-mode", "CURLP27", "--mwm", "7", "--milestone-start", "0", "--milestone-keys", "13", "--snapshot", "/snapshot.txt", "--max-depth", "1000"]
          readinessProbe:
            tcpSocket:
              port: 14265
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 4
          livenessProbe:
            tcpSocket:
              port: 14265
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 4
          ports:
            - containerPort: 14265
              name: iri-api
            - containerPort: 15600
              name: iri-peering-tcp
            - containerPort: 14600
              name: iri-peering-udp
          volumeMounts:
            - name: data
              mountPath: /iri/data
            - name: snapshot
              mountPath: /snapshot.txt
              subPath: snapshot.txt
#      nodeSelector:
#        failure-domain.beta.kubernetes.io/zone: eu-west-1c
      volumes:
        - name: snapshot
          configMap:
            name: snapshot
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

