

apiVersion: v1
clusters:
- cluster:
    server: https://C531EDF0A998F67394DC8879256B65FC.sk1.eu-west-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EZ3lNekV6TkRRek5Gb1hEVEk1TURneU1ERXpORFF6TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnZZClN2QVB3U2ZGWklyd0twMVRlVU1qeEpkMHppSVZoVEJlOG1YM1lBVVh2cHlETzFqc2d0Q3NmaGw0bjg2YUVuczIKUnl6TUNTUE1kV2xEWDQ1TXVZWGdKcGZSdGtZeVRHVUU0S1EyQlZ4TjN5cFRKeWhFSUJlMjliWnlmcjBEV3RnNQpSK2JQUWJQOW0xUmNkTjd6SkQ3Wjh5aVJjRGhyZ01LUnhzVlp4a1VwZExJcjJwVThZVzZ2SDNNSU1RNzd6MFRsCjJWRFJsZmd5eEJjN3FxYmdvWVVTZm5UOUdKb3ZwRFZNL1RIbVZVWDFkZzRkUUt2aWZzMzl1aXFINStvejVCNjAKUS9aTVMzK1FYUHRzeHVXdTU5aTlkd0VVOG4zU0lSdmVDL0xHUXNGUWh0M1NsRGZabU1DcC9BYjRGbVVxQTA3cwo4MCtZOUJ1Vk1qT0JvWUtmVEdrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKWTAvV09SSEJEZkxucHhKN3VuZ2NnS2tVZlgKUFkybm9lQUFQU2xLK2NIOHJFNGtXNk1RWjR2YWN1RU0vWEhJbUNydTVQYk9wNXpxOGZjR0lhN3N0VmErN1FMNgo0V2lJYWpTZVZiWmVBOVhUdEV5UnJsQi9OWmE3T280YVhTcXo0bHRteHNzZGJRYVY0Uko0V1ZjR1d0dERPa05WCjloWlNGNmRWVnJ0UjdScjdFTURsb3NBZEYxRklHaW8wekFua01mcWdjVlU1ZzY3NGw5TmFPN0pURkdUMUhBN3AKS2U3eWw0VHU0R1hlcWt1Q2JVTWhTa0I3YkNnOUJhZ3RsRE1YSDh3VlNwTy85a1NJNmhsU3VMNUl3RGs5NVk3eApXTzRRWGluOEtaR1ZCb0RmR2ROdlZBdFBiWE1VOEdqdG5BSHZ4SmlIOU5tQmZrL1lmMnlWT3h6eGNVcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - token
        - -i
        - eks

